[build]
buildCommand = "npm install && npm run build --workspace=packages/contracts && npm run build --workspace=backend && cd backend && npx prisma generate"

[deploy]
startCommand = "cd backend && npx prisma db push --skip-generate && npm run start:prod"
